# Generated by Django 5.0.7 on 2024-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_job_is_active_alter_job_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='interval_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='interval_value',
            field=models.IntegerField(default=1),
        ),
    ]
